version: '3.7'

services:
  app:
    build: ./app
    container_name: ${PROJECT_NAME}_app
    volumes:
      - ./app/backend:/var/www/html
      - ./app/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "${PHP_FPM_PORT}:9000"
    expose:
      - "${PHP_FPM_PORT}"
    depends_on:
      - db
    environment:
      TZ: "Asia/Tokyo"
      APP_URL: ${APP_URL}
      APP_ENV: ${APP_ENV}
    networks:
      default:

  nginx:
    build: ./nginx
    container_name: ${PROJECT_NAME}_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/var/www/frontend/
    depends_on:
      - app
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      # - "${NGINX_HOST_HTTPS_PORT}:443"
      # - "${NGINX_BACK_END_PORT}:${NGINX_BACK_END_PORT}"
      # - "${NGINX_FRONT_END_PORT}:${NGINX_FRONT_END_PORT}"
    environment:
      TZ: "Asia/Tokyo"
    networks:
      default:
        ipv4_address: ${SERVICE_NETWORK_IP}

  db:
    build: ./mysql
    container_name: ${PROJECT_NAME}_db
    volumes:
      - vue-rpg-store:/var/lib/mysql # データの永続化
      - ./mysql/sql:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      DB_USER: ${DB_USER}
      DB_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: "Asia/Tokyo"
    networks:
      default:

  # node:
  #   build: ./node
  #   container_name: ${PROJECT_NAME}_node
  #   volumes:
  #     - ./node/frontend:/frontend
  #   depends_on:
  #     - app
  #   ports:
  #     - "${NODE_APPLICATION_PORT}:${NODE_APPLICATION_PORT}"

  # redis:
  #   image: redis:5.0-alpine
  #   container_name: ${PROJECT_NAME}_redis
  #   volumes:
  #     - redis-store:/data

volumes:
  # redis-store:
  vue-rpg-store:
    name: ${VOLUME_NAME}
    driver: local

networks:
  default:
    external:
      name: ${NETWORK_NAME}
